# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dbdom}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Hamid"]
  s.date = %q{2010-03-29}
  s.default_executable = %q{install-deps.sh}
  s.description = %q{exposes a jdbc db via dom}
  s.email = %q{aaron.hamid@gmail.com}
  s.executables = ["install-deps.sh"]
  s.extra_rdoc_files = [
    "README",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/install-deps.sh",
     "dbdom.gemspec",
     "lib/advice.rb",
     "lib/dbdom.rb",
     "lib/jdbc.rb",
     "lib/rexml.rb",
     "lib/xerces.rb",
     "test.sh",
     "test/advice_test.rb",
     "test/dbdom_test.rb"
  ]
  s.homepage = %q{http://github.com/ahamid/dbdom}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{exposes a jdbc db via dom}
  s.test_files = [
    "test/advice_test.rb",
     "test/dbdom_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<maven_gem>, [">= 0"])
    else
      s.add_dependency(%q<maven_gem>, [">= 0"])
    end
  else
    s.add_dependency(%q<maven_gem>, [">= 0"])
  end
end

